export const INDUSTRIES_A_1 = [  {
    slug: 'auto-repair', biz: 'Shoreline Auto & Tire', industry: 'Auto Repair & Tires', emoji: '🚗',
    blurb: 'Repair orders, tire sales, and profit per car — live.',
    theme: { dark: '#1E2A38', accent: '#C0492F' },
    months: { rev: [61200, 59800, 63400, 66100, 70800, 64200, 58900, 57400, 62800, 65900, 67200, 68400], exp: [46800, 45900, 48200, 50100, 53400, 48800, 45200, 44600, 47900, 50200, 50800, 51300] },
    revCats: [['Tire sales', 29800], ['Repairs & service', 27200], ['Alignments & inspections', 6900], ['Detailing', 4500]],
    expLines: [
      { n: 'Parts & tires (COGS)', a: 26400, tx: [['6/26', 'ATD — American Tire Dist.', 9840], ['6/19', 'WorldPac parts order', 4210], ['6/12', 'NAPA Auto Parts', 2890]] },
      { n: 'Payroll', a: 14800, tx: [['6/30', 'Payroll run — 2 techs + advisor', 7400], ['6/15', 'Payroll run', 7400]] },
      { n: 'Rent', a: 4200, tx: [['6/1', 'Shoreline Plaza LLC', 4200]] },
      { n: 'Shop supplies', a: 1900, tx: [['6/22', 'Grainger', 640], ['6/9', 'Uline', 720], ['6/4', 'Local hardware', 540]] },
      { n: 'Insurance', a: 1600, tx: [['6/1', 'Garage keepers policy', 1600]] },
      { n: 'Software & misc', a: 2400, tx: [['6/1', 'Shop management software', 380], ['6/14', 'Card processing fees', 1120], ['6/28', 'Uniforms & laundry', 900]] },
    ],
    extraKpi: { k: 'CARS THROUGH THE SHOP', v: '312', sub: 'this month · avg $219/RO' },
    insights: [
      'Tires are 44% of your revenue but only ~18% margin — repairs and service carry the profit. June\'s mix shifted 3 points toward tires, which is why profit felt flat while the shop was slammed.',
      'Average repair order is $219. Shops that get to $260+ do it by converting inspections to estimates, not raising prices — at 312 cars/month, a $40 lift is ~$12K more revenue.',
      'That $9,840 ATD order in late June: quoting WorldPac against every $5K+ parts order is worth ~$1,000/month on a 4% swing.',
    ],
    extras: [
      {
        tab: 'Supplier Orders',
        kpis: [{ k: 'INVENTORY ON SHELF', v: '$84K', sub: 'at cost' }, { k: 'STOCK BUYS (JUN)', v: '$13,910', sub: 'hit Inventory, not COGS' }, { k: 'JOB PARTS (JUN)', v: '$5,150', sub: 'straight to COGS' }],
        modules: [{
          type: 'worklist', t: 'Supplier orders, classified', sub: 'Every parts order tagged the way your books need it — shelf stock vs. cost of a specific job',
          rows: [
            { a: 'ATD #88412 — 24 tires, mixed sizes', b: 'American Tire Distributors · 6/26', val: '$9,840', flag: { f: 'STOCK', tone: 'blue' } },
            { a: 'WorldPac — brake kits', b: 'Silverado RO #2214 · 6/19', val: '$4,210', flag: { f: 'COGS', tone: 'amber' } },
            { a: 'NAPA — filters & fluids restock', b: 'Shelf replenishment · 6/12', val: '$2,890', flag: { f: 'STOCK', tone: 'blue' } },
            { a: 'ATD #88371 — 4 Michelin Primacy', b: 'Camry RO #2196 · 6/9', val: '$940', flag: { f: 'COGS', tone: 'amber' } },
            { a: 'Interstate — battery order', b: 'Shelf replenishment · 6/4', val: '$1,180', flag: { f: 'STOCK', tone: 'blue' } },
          ],
          note: 'The PO# rule does the tagging automatically — stock hits Inventory, job parts hit COGS. Month-end stops being a guessing game.',
        }],
      },
      {
        tab: 'Tire Stock',
        modules: [{
          type: 'board', t: 'Tire stock by size & brand', sub: 'What is moving, what is sitting, what to reorder before the weekend',
          cols: ['SIZE / BRAND', 'ON HAND', 'SOLD (JUN)', 'AVG COST', 'RETAIL', 'MARGIN', ''],
          rows: [
            ['225/65R17 Michelin Defender', '18', '22', '$128', '$189', '32%', { f: 'REORDER', tone: 'red' }],
            ['265/70R17 BFG KO2', '24', '15', '$142', '$215', '34%', { f: 'HEALTHY', tone: 'green' }],
            ['205/55R16 Firestone', '31', '19', '$84', '$132', '36%', { f: 'HEALTHY', tone: 'green' }],
            ['275/55R20 Nitto', '9', '11', '$167', '$259', '36%', { f: 'LOW', tone: 'amber' }],
            ['195/65R15 Kumho', '42', '6', '$61', '$98', '38%', { f: 'SLOW MOVER', tone: 'amber' }],
            ['235/45R18 Continental', '2', '8', '$138', '$209', '34%', { f: 'REORDER', tone: 'red' }],
          ],
          note: 'Same stock view pattern we ship for tire shops — shelf vs job parts, not a fake dashboard.',
        }],
      },
    ],
    ops: {
      type: 'jobs', unit: 'RO', label: 'Repair Orders', title: 'Open repair orders', sub: 'Change a status or add an RO — in your build this is your live shop board',
      cols: ['REPAIR ORDER', 'TECH', 'STATUS', 'CHARGED', 'PROFIT'],
      kpis: [{ k: 'CARS IN THE SHOP', v: '7', sub: '3 waiting on parts' }, { k: 'BILLED TODAY', v: '$2,840', sub: '9 tickets closed' }, { k: 'AVG PROFIT / RO', v: '$96', sub: 'after parts + labor' }],
      rows: [
        { a: 'Silverado 2500 — brakes + rotors', b: 'M. Alvarez · drop-off', who: 'Danny', s: 'in_progress', chg: 780, cost: 410 },
        { a: 'Camry — 4 tires + alignment', b: 'S. Rothman · waiting', who: 'Pete', s: 'in_progress', chg: 940, cost: 660 },
        { a: 'F-150 — AC not blowing cold', b: 'Ocean Landscaping (fleet)', who: 'Danny', s: 'waiting', chg: 620, cost: 285 },
        { a: 'Odyssey — timing belt + water pump', b: 'R. Chen · scheduled Thu', who: 'Pete', s: 'scheduled', chg: 1180, cost: 540 },
        { a: 'Jetta — check engine diag', b: 'K. Williams', who: 'Danny', s: 'done', chg: 165, cost: 20 },
        { a: 'Wrangler — lift kit install', b: 'T. Brennan', who: 'Pete', s: 'done', chg: 1450, cost: 890 },
      ],
    },
  },
  {
    slug: 'hvac', biz: 'Coastal Air Heating & Cooling', industry: 'HVAC', emoji: '❄️',
    blurb: 'Installs vs. service calls, profit per job, seasonal swings.',
    theme: { dark: '#16323E', accent: '#E07A3C' },
    months: { rev: [88400, 84200, 61800, 52400, 58900, 71200, 76800, 68400, 55200, 59800, 78400, 92600], exp: [65200, 62400, 47800, 41200, 45600, 54300, 58200, 52100, 43400, 46200, 59400, 68900] },
    revCats: [['Installs & replacements', 54000], ['Service calls', 26800], ['Maintenance plans', 11800]],
    expLines: [
      { n: 'Equipment & parts', a: 34200, tx: [['6/24', 'Ferguson HVAC Supply', 12400], ['6/17', 'Johnstone Supply', 8900], ['6/6', 'Carrier distributor — 2 condensers', 9200]] },
      { n: 'Payroll', a: 21500, tx: [['6/30', 'Payroll — 3 techs + office', 10750], ['6/15', 'Payroll run', 10750]] },
      { n: 'Vehicles & fuel', a: 4800, tx: [['6/28', 'Fleet fuel card', 2140], ['6/20', 'Van 2 — brake service', 890], ['6/8', 'Fleet fuel card', 1770]] },
      { n: 'Rent & warehouse', a: 3600, tx: [['6/1', 'Industrial park unit 4B', 3600]] },
      { n: 'Insurance', a: 2900, tx: [['6/1', 'GL + workers comp', 2900]] },
      { n: 'Marketing', a: 1900, tx: [['6/15', 'Google Local Services ads', 1250], ['6/3', 'Yard signs & truck decals', 650]] },
    ],
    extraKpi: { k: 'MAINTENANCE PLANS', v: '118', sub: 'recurring revenue base' },
    insights: [
      'June did $92.6K — install season. But look at October: $52.4K. Banking ~$8K/month now is what covers winter payroll without sweating it.',
      'Maintenance plans are only 13% of revenue but they smooth the whole curve. You have 118 plans; at 160, your fixed costs are covered before a single install.',
      'Equipment ate 37% of June spend, and installs are running roughly 2× the margin of service calls per crew-day — every extra install day is worth ~$1,900 in profit.',
    ],
    extras: [
      {
        tab: 'Quote Builder',
        modules: [{
          type: 'quote', t: 'Quote an install — margin before you send it', sub: 'Pick the system, set the hours, and the number is ready before you leave the kitchen table',
          systems: [['3-ton Trane XR14 + air handler', 4100, 16], ['2-ton condenser swap', 2400, 10], ['4-ton full system + ductwork', 6800, 28], ['2-zone Mitsubishi mini-split', 2900, 14], ['Rooftop unit — light commercial', 5400, 20]],
          rate: 95, permitCost: 240,
          note: 'In your build this pulls your real equipment costs and labor rates — and every quote logs to a pipeline so none go cold.',
        }],
      },
      {
        tab: 'Contracts',
        kpis: [{ k: 'PLANS ACTIVE', v: '118', sub: '$11.8K/mo recurring' }, { k: 'VISITS DUE (30d)', v: '14', sub: '2 overdue' }, { k: 'RENEWALS (30d)', v: '9', sub: 'worth $6,400/yr' }],
        modules: [{
          type: 'worklist', t: 'Maintenance contracts', sub: 'Who you cover, how often, and what is coming due — instead of a notebook in the truck', act: 'MARK SCHEDULED',
          rows: [
            { a: 'Marino residence', b: '2 visits/yr · $189/yr', val: '', meta: 'visit overdue 12 days', flag: { f: 'OVERDUE', tone: 'red' } },
            { a: 'Bayshore Dental — 2 rooftop units', b: '4 visits/yr · $1,880/yr', val: '', meta: 'visit due in 6 days', flag: { f: 'DUE SOON', tone: 'amber' } },
            { a: 'Hoffman residence', b: '2 visits/yr · $189/yr', val: '', meta: 'visit due in 14 days', flag: { f: 'DUE SOON', tone: 'amber' } },
            { a: 'K. Patel', b: '2 visits/yr · $189/yr', val: '', meta: 'renewal in 9 days', flag: { f: 'RENEWAL', tone: 'blue' } },
            { a: 'Shore Motel — 16 PTAC units', b: 'quarterly · $3,400/yr', val: '', meta: 'renewal in 21 days', flag: { f: 'RENEWAL', tone: 'blue' } },
            { a: 'Riverside Café — walk-in + refrigeration', b: 'quarterly · $2,100/yr', val: '', meta: 'current — next visit Sep', flag: { f: 'ON TRACK', tone: 'green' } },
          ],
          note: 'Reminders fire before visits and renewals — the recurring base stops leaking.',
        }],
      },
    ],
    ops: {
      type: 'jobs', label: 'Jobs', title: 'Job board', sub: 'Installs and calls, with profit per job as parts and labor hit',
      cols: ['JOB', 'TECH', 'STATUS', 'CHARGED', 'PROFIT'],
      kpis: [{ k: 'OPEN JOBS', v: '11', sub: '6 scheduled this week' }, { k: 'INSTALLS THIS MONTH', v: '9', sub: 'avg $6,000 ticket' }, { k: 'FIRST-VISIT FIX RATE', v: '84%', sub: 'service calls' }],
      rows: [
        { a: 'Bayshore Dental — 3-ton install', b: 'Trane XR14 + air handler', who: 'Rob', s: 'in_progress', chg: 6800, cost: 4100 },
        { a: 'Marino residence — AC no cool', b: 'Capacitor + refrigerant', who: 'Steve', s: 'done', chg: 480, cost: 140 },
        { a: 'Shore Motel — 4 PTAC units', b: 'Replace units 12–15', who: 'Rob', s: 'scheduled', chg: 5200, cost: 3400 },
        { a: 'K. Patel — mini-split install', b: '2-zone Mitsubishi', who: 'Jimmy', s: 'waiting', chg: 4600, cost: 2900 },
        { a: 'Riverside Café — walk-in cooler', b: 'Compressor swap', who: 'Steve', s: 'in_progress', chg: 2100, cost: 1180 },
        { a: 'Hoffman residence — tune-up', b: 'Maintenance plan visit', who: 'Jimmy', s: 'done', chg: 129, cost: 25 },
      ],
    },
  },
  {
    slug: 'plumbing', biz: 'BlueLine Plumbing', industry: 'Plumbing', emoji: '🚿',
    blurb: 'Service calls, remodels, and water heaters — margin on every job.',
    theme: { dark: '#1B2F4B', accent: '#2C6E9B' },
    months: { rev: [69800, 71200, 68400, 72600, 75800, 78200, 81400, 74600, 70200, 72800, 73400, 74200], exp: [51200, 52400, 50100, 53200, 55400, 57100, 59200, 54600, 51400, 53200, 53600, 54100] },
    revCats: [['Service & repair', 38400], ['Remodels & rough-in', 24600], ['Water heaters', 11200]],
    expLines: [
      { n: 'Materials & fixtures', a: 22800, tx: [['6/25', 'Ferguson Plumbing Supply', 8400], ['6/18', 'Home Depot Pro', 3200], ['6/10', 'AO Smith — 4 water heaters', 4900]] },
      { n: 'Payroll', a: 19600, tx: [['6/30', 'Payroll — 3 plumbers + apprentice', 9800], ['6/15', 'Payroll run', 9800]] },
      { n: 'Vehicles & fuel', a: 4300, tx: [['6/27', 'Fleet fuel', 1980], ['6/12', 'Van 1 — tires', 840], ['6/5', 'Fleet fuel', 1480]] },
      { n: 'Insurance', a: 2700, tx: [['6/1', 'GL + workers comp', 2700]] },
      { n: 'Permits & inspections', a: 1400, tx: [['6/20', 'Township permits ×3', 860], ['6/6', 'Backflow certifications', 540]] },
      { n: 'Rent & misc', a: 3300, tx: [['6/1', 'Shop rent', 2200], ['6/14', 'Answering service', 420], ['6/1', 'Software & GPS', 680]] },
    ],
    extraKpi: { k: 'AVG SERVICE TICKET', v: '$342', sub: 'up from $305 last quarter' },
    insights: [
      'Service & repair is 52% of June revenue and runs roughly double the per-hour margin of remodel work — protect those emergency slots.',
      '14 water heaters in June at ~$800 installed. Attaching a heater quote to every service call over $300 converts about 1 in 9 — that\'s 4 more heaters a month sitting in your own call log.',
      'Vehicles + fuel hit $4,300. Clustering jobs by township on set days could pull ~15% of that back without touching the schedule.',
    ],
    extras: [
      {
        tab: 'Emergency Margin',
        modules: [{
          type: 'segments', t: 'Emergency vs. scheduled — same crew, different money', sub: 'Why the 2am call is worth protecting',
          segs: [
            { name: 'EMERGENCY', hot: true, lines: [['Jobs (Jun)', '31'], ['Avg ticket', '$612'], ['Labor hrs/job', '2.1']], foot: ['Margin', '58%'] },
            { name: 'SCHEDULED SERVICE', lines: [['Jobs (Jun)', '64'], ['Avg ticket', '$342'], ['Labor hrs/job', '2.4']], foot: ['Margin', '39%'] },
            { name: 'REMODEL / ROUGH-IN', lines: [['Jobs (Jun)', '6'], ['Avg ticket', '$4,100'], ['Labor hrs/job', '38']], foot: ['Margin', '31%'] },
          ],
          note: 'Every emergency slot you protect is worth roughly 1.5 scheduled jobs. Answer the phone at 2am — but charge like it.',
        }],
      },
      {
        tab: 'A/R & Heaters',
        modules: [
          {
            type: 'worklist', t: 'Who owes you', sub: 'Open invoices, oldest first', act: 'SEND REMINDER',
            rows: [
              { a: 'Lakewood duplex GC — rough-in', b: 'Invoice #1182', val: '$6,200', meta: '54 days', flag: { f: '60+ DAYS', tone: 'red' } },
              { a: 'Toms River Diner — grease trap', b: 'Invoice #1201', val: '$1,450', meta: '31 days', flag: { f: '31–60 DAYS', tone: 'amber' } },
              { a: 'Shore Pines HOA — backflow tests', b: 'Invoice #1214', val: '$720', meta: '18 days', flag: { f: 'CURRENT', tone: 'green' } },
              { a: 'B. Katz — water heater', b: 'Invoice #1219', val: '$1,850', meta: '9 days', flag: { f: 'CURRENT', tone: 'green' } },
            ],
            note: 'One reminder button beats an awkward phone call. In your build these send automatically at 30 and 45 days.',
          },
          {
            type: 'worklist', t: 'Water-heater funnel', sub: 'Every service call over $300 gets a heater quote — about 1 in 9 says yes', act: 'QUOTE IT',
            rows: [
              { a: 'M. Osei — faucet & disposal call', b: 'Heater is 11 years old', val: '$1,850', flag: { f: 'QUOTE OPEN', tone: 'amber' } },
              { a: 'Delgado residence — repipe', b: 'Heater is 14 years old, quoted at walkthrough', val: '$2,100', flag: { f: 'QUOTE OPEN', tone: 'amber' } },
              { a: 'R. Chen — service call', b: 'Installed 6/22', val: '$1,790', flag: { f: 'WON', tone: 'green' } },
              { a: 'Sandpiper Motel', b: '2 aging commercial units', val: '$5,400', flag: { f: 'QUOTE OPEN', tone: 'amber' } },
            ],
            note: '14 heaters went in last month. The funnel is where the 15th comes from.',
          },
        ],
      },
    ],
    ops: {
      type: 'jobs', label: 'Jobs', title: 'Job board', sub: 'Every open job with live cost vs. charged',
      cols: ['JOB', 'PLUMBER', 'STATUS', 'CHARGED', 'PROFIT'],
      kpis: [{ k: 'OPEN JOBS', v: '9', sub: '2 emergencies today' }, { k: 'WATER HEATERS (MTD)', v: '14', sub: 'avg $800 installed' }, { k: 'CALLBACK RATE', v: '2.1%', sub: 'trailing 90 days' }],
      rows: [
        { a: 'Toms River Diner — grease trap', b: 'Emergency — backed up', who: 'Vic', s: 'in_progress', chg: 1450, cost: 620 },
        { a: 'Delgado residence — repipe', b: 'Whole-house PEX, day 2 of 3', who: 'Sal', s: 'in_progress', chg: 8900, cost: 5200 },
        { a: 'B. Katz — 50-gal water heater', b: 'Replace + expansion tank', who: 'Vic', s: 'scheduled', chg: 1850, cost: 1080 },
        { a: 'Lakewood duplex — bath remodel', b: 'Rough-in, GC: Cornerstone', who: 'Sal', s: 'waiting', chg: 6200, cost: 3600 },
        { a: 'M. Osei — kitchen faucet + disposal', b: 'Customer-supplied fixture', who: 'Eddie', s: 'done', chg: 380, cost: 95 },
        { a: 'Shore Pines HOA — irrigation backflow', b: 'Annual test, 6 devices', who: 'Eddie', s: 'done', chg: 720, cost: 140 },
      ],
    },
  },
  {
    slug: 'electrician', biz: 'Amped Electric', industry: 'Electrical Contracting', emoji: '⚡',
    blurb: 'Residential service, commercial contracts, panel upgrades.',
    theme: { dark: '#21262E', accent: '#D9A62E' },
    months: { rev: [56200, 57800, 59400, 58200, 60800, 62400, 59800, 57200, 58900, 60400, 61200, 61800], exp: [40800, 41900, 42800, 42100, 43900, 45200, 43400, 41600, 42700, 43800, 44200, 44500] },
    revCats: [['Residential service', 27400], ['Commercial contracts', 24800], ['Panel upgrades & EV chargers', 9600]],
    expLines: [
      { n: 'Materials & fixtures', a: 17900, tx: [['6/26', 'Cooper Electric Supply', 7200], ['6/16', 'Graybar', 5400], ['6/8', 'Home Depot Pro', 2100]] },
      { n: 'Payroll', a: 16800, tx: [['6/30', 'Payroll — 2 journeymen + helper', 8400], ['6/15', 'Payroll run', 8400]] },
      { n: 'Vehicles & fuel', a: 3600, tx: [['6/28', 'Fleet fuel', 1650], ['6/11', 'Van registration + tolls', 480], ['6/4', 'Fleet fuel', 1470]] },
      { n: 'Insurance', a: 2400, tx: [['6/1', 'GL + workers comp', 2400]] },
      { n: 'Tools & equipment', a: 1500, tx: [['6/19', 'Milwaukee — replacement kit', 890], ['6/7', 'Test equipment calibration', 610]] },
      { n: 'Rent & misc', a: 2300, tx: [['6/1', 'Shop rent', 1500], ['6/1', 'Software & phones', 800]] },
    ],
    extraKpi: { k: 'EV CHARGERS (MTD)', v: '6', sub: 'fastest-growing line' },
    insights: [
      'Commercial is 40% of revenue but pays in 45+ days; residential pays same-day. Your mid-month cash dip is timing, not performance — now you can see it coming.',
      'EV chargers: 6 in June, best margin in the shop, and growing. Put it on every invoice footer — your own customer list is the cheapest lead source you have.',
      'There\'s $34K sitting in pending estimates at a 61% win rate. A same-week follow-up call moves roughly 1 in 5 of those — worth more than any new ad spend.',
    ],
    extras: [
      {
        tab: 'Estimates',
        kpis: [{ k: 'PENDING', v: '$34K', sub: '11 quotes out' }, { k: 'WIN RATE', v: '61%', sub: 'trailing 90 days' }, { k: 'GONE COLD', v: '2', sub: 'no touch in 3+ weeks' }],
        modules: [{
          type: 'worklist', t: 'Estimate pipeline', sub: 'A same-week follow-up call moves 1 in 5 of these', act: 'FOLLOW UP',
          rows: [
            { a: 'Toms River Twp — field lighting', b: 'Sent 5/28', val: '$12,600', meta: '31 days out', flag: { f: 'GONE COLD', tone: 'red' } },
            { a: 'Bayville office park — panel + circuits', b: 'Sent 6/2', val: '$8,400', meta: '26 days out', flag: { f: 'GONE COLD', tone: 'red' } },
            { a: 'Ocean Dental — renovation circuits', b: 'Sent 6/12', val: '$5,200', meta: '16 days out', flag: { f: 'FOLLOW UP', tone: 'amber' } },
            { a: 'H. Nguyen — 200A panel upgrade', b: 'Sent 6/18', val: '$3,400', meta: '10 days out', flag: { f: 'FOLLOW UP', tone: 'amber' } },
            { a: 'Shore Motel — exterior lighting ph.2', b: 'Sent 6/24', val: '$2,850', meta: '4 days out', flag: { f: 'FRESH', tone: 'green' } },
            { a: 'R. Feldman — EV charger #2', b: 'Sent 6/25', val: '$1,250', meta: '3 days out', flag: { f: 'FRESH', tone: 'green' } },
          ],
          note: 'At your 61% win rate, the two cold ones alone are ~$12.8K of expected revenue sitting in voicemail.',
        }],
      },
      {
        tab: 'A/R & EV',
        modules: [
          {
            type: 'segments', t: 'When the money actually lands', sub: 'Commercial work pays more — and later',
            segs: [
              { name: 'RESIDENTIAL', lines: [['Invoices (Jun)', '24'], ['Avg days to pay', '2'], ['Outstanding', '$1,850']], foot: ['Share of revenue', '44%'] },
              { name: 'COMMERCIAL', hot: true, lines: [['Invoices (Jun)', '11'], ['Avg days to pay', '47'], ['Outstanding', '$28,400']], foot: ['Share of revenue', '40%'] },
              { name: 'PANELS & EV', lines: [['Invoices (Jun)', '9'], ['Avg days to pay', '8'], ['Outstanding', '$3,200']], foot: ['Share of revenue', '16%'] },
            ],
            note: 'The mid-month cash dip is commercial float, not a slow business. Now it is visible instead of scary.',
          },
          {
            type: 'board', t: 'EV charger installs — the growth line', sub: 'Best margin in the shop, and every install markets the next one',
            cols: ['JOB', 'DATE', 'CHARGED', 'COST', 'MARGIN', 'CAME FROM'],
            rows: [
              ['R. Feldman — Tesla wall connector', '6/25', '$1,250', '$520', '58%', 'Referral'],
              ['M. Grasso — Level 2 + subpanel', '6/18', '$2,100', '$980', '53%', 'Invoice footer'],
              ['Bayside condo — shared charger', '6/11', '$3,800', '$1,900', '50%', 'Property manager'],
              ['K. Brooks — Level 2', '6/6', '$1,180', '$540', '54%', 'Google'],
            ],
            note: '6 installs in June, 4 referral sources. Put it on every invoice footer — your customer list is the cheapest ad you own.',
          },
        ],
      },
    ],
    ops: {
      type: 'jobs', label: 'Jobs', title: 'Job board', sub: 'Track every job from estimate to paid',
      cols: ['JOB', 'ELECTRICIAN', 'STATUS', 'CHARGED', 'PROFIT'],
      kpis: [{ k: 'OPEN JOBS', v: '8', sub: '3 commercial' }, { k: 'ESTIMATES OUT', v: '$34K', sub: '11 pending approval' }, { k: 'WIN RATE', v: '61%', sub: 'trailing 90 days' }],
      rows: [
        { a: 'Bayville Fitness — lighting retrofit', b: 'LED conversion, 84 fixtures', who: 'Marc', s: 'in_progress', chg: 12800, cost: 7900 },
        { a: 'H. Nguyen — 200A panel upgrade', b: 'Permit approved', who: 'Dre', s: 'scheduled', chg: 3400, cost: 1750 },
        { a: 'Ocean Twp office — new circuits', b: '6 dedicated circuits, server room', who: 'Marc', s: 'waiting', chg: 2900, cost: 1420 },
        { a: 'R. Feldman — EV charger', b: 'Tesla wall connector, 60A', who: 'Dre', s: 'done', chg: 1250, cost: 520 },
        { a: 'Sandpiper Motel — exterior lighting', b: 'Photocells + timers', who: 'Dre', s: 'in_progress', chg: 1850, cost: 880 },
        { a: 'K. Brooks — troubleshoot flickering', b: 'Diagnostic call', who: 'Marc', s: 'done', chg: 220, cost: 30 },
      ],
    },
  },]
