// Featured on the homepage iframe picker. Fictitious demo businesses only —
// each tab is chosen to show a different product idea we actually build.
// DemoPreview loads these with ?embed=1 (see lib/demoEmbed.js).

export const FEATURED_DEMOS = [
  {
    biz: 'Summit Snacks Co.',
    label: 'Packaged snacks & consignment',
    src: '/demo',
    emoji: '🥜',
    accent: '#2A6CB8',
    caption: 'Store partners, shelf counts, collections, and channel P&L next to QuickBooks at close.',
  },
  {
    biz: 'Riverstone Roofing',
    label: 'Roofing',
    src: '/riverstone-roofing',
    emoji: '🏘️',
    accent: '#035CEB',
    caption: 'Job margin flags, WIP schedule, claim-aware cash flow, buyer package.',
  },
  {
    biz: 'Riverbend Fence Co.',
    label: 'Fencing',
    src: '/riverbend-fence',
    emoji: '🪵',
    accent: '#5C4A32',
    caption: 'Crew logs a day from a phone. Lands in QuickBooks coded to the job.',
  },
  {
    biz: 'Riverfall Gowns',
    label: 'Bridal shop',
    src: '/riverfall-gowns',
    emoji: '👗',
    accent: '#B14D6A',
    caption: 'Orders, deposits, alterations queue. Owner and staff on different screens.',
  },
  {
    biz: 'Harborfield Residential',
    label: 'Property mgmt',
    src: '/harborfield-properties',
    emoji: '🏠',
    accent: '#4A7BA8',
    caption: 'Rent roll, delinquency tracking, and owner statements across the portfolio.',
  },
  {
    biz: 'Northline Global',
    label: 'Import & distro',
    src: '/northline-global',
    emoji: '📦',
    accent: '#C9A84C',
    caption: 'PO pipeline with landed cost, warehouse bins, and margin per order.',
  },
  {
    biz: 'Metro Wholesale',
    label: 'Wholesale',
    src: '/demos/wholesale',
    emoji: '🚚',
    accent: '#2D6A4F',
    caption: 'Route accounts, store invoicing, and books that stay in sync.',
  },
  {
    biz: 'Lakeland Supply Co.',
    label: 'Collections',
    src: '/ar-desk',
    emoji: '📬',
    accent: '#2CA01C',
    caption: 'Open invoices from QuickBooks. Bulk statements from your own email.',
  },
  {
    biz: 'Riverside Tires',
    label: 'Tire shop',
    src: '/riverside-tires',
    emoji: '🔩',
    accent: '#B0281C',
    caption: 'Clover tickets matched to distributor cost — margin per RO during the month.',
  },
  {
    biz: 'Riverbank Funding',
    label: 'Lending',
    src: '/sba-lending',
    emoji: '🏦',
    accent: '#1F6FB2',
    caption: 'Deal pipeline and fees — operating view on QuickBooks, not loan servicing software.',
  },
]
